default:
  image: debian:13-slim
  # services:
  #   - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:29-dind-rootless
  #     alias: docker
  # before_script: |
  #   apt-get install -y docker-cli openjdk-25-jdk-headless

build:
  script: |
    echo "Hello World"