services:
  postgres:
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s # Grace period for initial startup
    ports:
      - 15433:5432
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dependency_proxy}
      POSTGRES_USER: ${POSTGRES_USER:-dependency_proxy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dependency_proxy}

  webapp:
    image: weeksconsulting-us/dependency-proxy:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-dependency_proxy}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-dependency_proxy}
      LOGGING_LEVEL_US_WEEKSCONSULTING: DEBUG
      SPRING_APPLICATION_JSON: |
        {
          "application": {
            "cleanup": {
              "schedule": "10s"
              },
            "repositories": {
              "raw": {
                "apache": {
                  "base_url": "https://dlcdn.apache.org",
                  "cache_ttl": "10s"
                },
                "nodejs": {
                  "base_url": "https://dist.nodejs.org",
                  "cache_ttl": "10s"
                },
                "debian": {
                  "base_url": "http://deb.debian.org",
                  "cache_ttl": "10s",
                  "excludes": [
                    "/debian/dists/",
                    "/debian-security/dists/"
                    ]          
                }
              }
            }
          }
        }

volumes:
  db_data:
  cache_data: