services:
  postgres:
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s # Grace period for initial startup
    ports:
      - 15433:5432
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${PROXY_DB_DATABASE:-postgres}
      POSTGRES_USER: ${PROXY_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PROXY_DB_PASSWORD:-postgres}

  webapp:
    image: ghcr.io/weeks-consulting/dependency-proxy:0.0.1
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PROXY_DB_DATABASE: ${PROXY_DB_DATABASE:-postgres}
      PROXY_DB_USERNAME: ${PROXY_DB_USERNAME:-postgres}      
      PROXY_DB_PASSWORD: ${PROXY_DB_PASSWORD:-postgres}
      PROXY_LOG_LEVEL: DEBUG
      SPRING_APPLICATION_JSON: |
        {
          "application": {
            "repositories": {
              "raw": {
                "apache": {
                  "base_url": "https://dlcdn.apache.org",
                  "cache_ttl": "10m"
                },
                "npm": {
                  "base_url": "https://registry.npmjs.org",
                  "cache_ttl": "10m"
                },
                "debian": {
                  "base_url": "http://deb.debian.org",
                  "cache_ttl": "10m",
                  "excludes": [
                    "/debian/dists/",
                    "/debian-security/dists/"
                  ]
                },
                "rocky": {
                  "base_url": "http://dl.rockylinux.org",
                  "cache_ttl": "10m",
                  "excludes": [
                    "/pub/rocky/9/BaseOS/x86_64/os/repodata/",
                    "/pub/rocky/9/AppStream/x86_64/os/repodata/",
                    "/pub/rocky/9/extras/x86_64/os/repodata/"
                  ]
                }
              }
            }
          }
        }

volumes:
  db_data:
  cache_data: