spring:
  application:
    name: dependency-proxy
  cloud:
    aws:
      s3:
        region: us-east-1

  mvc:
    async:
      request-timeout: 300000

logging:
  level:
    org.springframework: INFO