name: Cleanup Untagged Container images

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  cleanup:
    name: Cleanup Untagged Images
    runs-on: ubuntu-latest
    permissions:
      packages: write    
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1