name: Spring Boot Image Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25'
          cache: maven

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Spring Boot Image
        run: |
          MVN_RELEASE_VERSION="$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" && \
          SPRING_BOOT_IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}" && \
          SPRING_BOOT_IMAGE_TAGS="${MVN_RELEASE_VERSION,,},latest" && \          
          echo "Publishing ${SPRING_BOOT_IMAGE_NAME} to Tags ${SPRING_BOOT_IMAGE_NAME}" && \
          ./mvnw spring-boot:build-image --batch-mode --no-transfer-progress \
            -DskipTests \
            -Ddocker.publishRegistry.url="ghcr.io" \
            -Dspring-boot.build-image.publish="true" \
            -Dspring-boot.build-image.imageName="${SPRING_BOOT_IMAGE_NAME}" \
            -Dspring-boot.build-image.tags="${SPRING_BOOT_IMAGE_TAGS}"
