name: Spring Boot Image Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          ./mvnw clean spring-boot:build-image -Pnative  -DskipTests